import type { Profile } from "@/content/types";

export const profile: Profile = {
  headline: "Frontend sênior com visão de produto e de processo.",
  bio: [
    "Sou desenvolvedor frontend sênior e trabalho com desenvolvimento web desde outubro de 2018, quando migrei de área. Passei por oito empresas, em produtos de e-commerce, educação, saúde, telecom, indústria e logística, construindo de interfaces responsivas a dashboards corporativos.",
    "Já fui o único desenvolvedor frontend de um produto, responsável pela stack e pela arquitetura, e atuei em times maiores modernizando sistemas legados e automatizando build e deploy em nuvem.",
    "Antes da tecnologia, me formei tecnólogo em Logística e fiz pós-graduação em Administração Empresarial. Essa base me ajuda a entender a operação e o negócio antes de desenhar a tela. Hoje também uso IA no dia a dia de engenharia e curso pós-graduação em Inteligência Artificial e Ciência de Dados.",
  ],
  expertise: [
    {
      title: "Interfaces e produto",
      description: "Aplicações e sites rápidos, acessíveis e responsivos, do componente ao fluxo completo.",
      items: ["React e Next.js", "TypeScript", "Tailwind CSS e Shadcn/UI", "Acessibilidade e UI/UX"],
    },
    {
      title: "Dashboards e integrações",
      description: "Painéis que organizam dados da operação e se conectam a APIs e sistemas corporativos.",
      items: ["Dashboards de dados", "APIs REST", "Autenticação JWT", "Modernização de legado"],
    },
    {
      title: "Entrega e IA aplicada",
      description: "Pipelines que colocam o código em produção e IA usada onde traz ganho real.",
      items: ["CI/CD e Azure DevOps", "Docker e Azure", "Claude Code, Gemini e Copilot", "Prompt Engineering e RAG"],
    },
  ],
  experience: [
    {
      id: "mwm",
      company: "MWM Motores e Geradores",
      role: "Senior Frontend Engineer",
      start: "2025-09",
      end: "2026-09",
      place: "São Paulo · Híbrido",
      summary: "Frontend de sistemas corporativos e logísticos, do componente à infraestrutura no Azure.",
      highlights: [
        "Construí SPAs e PWAs em React, TypeScript e Vite para o MWM Portal e o Bio Plantas.",
        "Entreguei dashboards de logística e qualidade que centralizaram a gestão de portaria, cooperados e dados operacionais.",
        "Modernizei interfaces legadas para Tailwind CSS e Shadcn/UI, com mais responsividade e acessibilidade.",
        "Automatizei build e deploy com Docker, Azure Container Apps, ACR e pipelines no Azure DevOps.",
        "Integrei o frontend a APIs REST em Java Spring Boot e configurei servidores Nginx.",
      ],
      stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Shadcn/UI", "Docker", "Azure", "Spring Boot"],
    },
    {
      id: "portal-telemedicina",
      company: "Portal Telemedicina",
      role: "Frontend Engineer Sênior",
      start: "2024-10",
      end: "2025-01",
      place: "Barueri, SP · Remoto",
      summary: "Interfaces para uma plataforma de telemedicina em Angular.",
      highlights: [
        "Desenvolvi interfaces responsivas e acessíveis com Angular e TypeScript.",
        "Traduzi layouts em código, aplicando princípios de UI/UX e testes.",
        "Integrei APIs e serviços com entrega contínua via GitHub Actions.",
      ],
      stack: ["Angular", "TypeScript", "GitHub Actions"],
    },
    {
      id: "olos",
      company: "Olos Tecnologia",
      role: "Frontend Engineer Pleno",
      start: "2023-10",
      end: "2024-06",
      place: "São Paulo, SP",
      summary: "Produtos web em React e Next.js com foco em UI/UX.",
      highlights: [
        "Desenvolvi interfaces com React, Next.js, TypeScript, Styled Components e Material UI.",
        "Implementei layouts responsivos seguindo boas práticas de UI/UX.",
        "Mantive pipelines de CI/CD no GitHub Actions.",
      ],
      stack: ["React", "Next.js", "TypeScript", "Material UI"],
    },
    {
      id: "safira",
      company: "SAFIRA Soluções & Tecnologia",
      role: "Frontend Engineer Pleno",
      start: "2022-03",
      end: "2023-09",
      place: "São Paulo · Híbrido",
      summary: "Único desenvolvedor frontend do produto, responsável pela stack e pela arquitetura.",
      highlights: [
        "Defini a stack e estruturei a arquitetura frontend de ponta a ponta.",
        "Criei uma biblioteca de componentes reutilizáveis em React e TypeScript, autenticação JWT e integrações REST.",
        "Tomei decisões técnicas de performance, escalabilidade e segurança e orientei desenvolvedores juniores.",
        "Atuei com cloud AWS e Azure e esteiras de CI/CD.",
      ],
      stack: ["React", "TypeScript", "JWT", "AWS", "Azure"],
    },
    {
      id: "clude",
      company: "Clude, Cartão de Saúde 360°",
      role: "Analista Desenvolvedor Frontend",
      start: "2020-02",
      end: "2022-03",
      place: "São Paulo, SP",
      summary: "Aplicações web de saúde em React.",
      highlights: [
        "Desenvolvi aplicações web responsivas com React, JavaScript, Sass e Bootstrap.",
        "Entreguei soluções focadas em usabilidade e experiência do usuário.",
      ],
      stack: ["React", "JavaScript", "Sass", "Bootstrap"],
    },
    {
      id: "saraiva",
      company: "Saraiva",
      role: "Desenvolvedor Frontend",
      start: "2019-12",
      end: "2020-02",
      place: "São Paulo, SP",
      summary: "E-commerce de grande varejo na plataforma VTEX.",
      highlights: [
        "Desenvolvi páginas e componentes da loja virtual com HTML, Sass, JavaScript (jQuery) e Vue.js.",
        "Trabalhei com o VTEX Admin (CMS, Checkout, Master Data) e as APIs da VTEX: catálogo, checkout, logística, marketplace, OMS e vale-presente.",
      ],
      stack: ["VTEX", "Vue.js", "JavaScript", "jQuery", "Sass", "Gulp"],
    },
    {
      id: "edulabzz",
      company: "Edulabzz",
      role: "Desenvolvedor Frontend",
      start: "2019-07",
      end: "2019-10",
      place: "São Paulo, SP",
      summary: "Aplicações web para uma empresa de tecnologia educacional.",
      highlights: [
        "Desenvolvi interfaces web com HTML5, Sass, JavaScript, jQuery, Bootstrap e Material Design.",
        "Automatizei tarefas de build e gerenciei pacotes com npm e Yarn.",
      ],
      stack: ["JavaScript", "jQuery", "Sass", "Bootstrap", "Material Design"],
    },
    {
      id: "smartest",
      company: "Smartest IT Solutions",
      role: "Desenvolvedor Frontend (Freelancer)",
      start: "2018-10",
      end: "2019-06",
      place: "São Paulo, SP",
      summary: "Primeira experiência depois da migração de área: projetos web sob demanda.",
      highlights: [
        "Analisei e corrigi bugs e desenvolvi novas funcionalidades com JavaScript, React, Vue.js, TypeScript e Node.js.",
        "Consumi APIs REST, usei Firebase e MySQL e publiquei aplicações estáticas com Webpack.",
      ],
      stack: ["React", "Vue.js", "TypeScript", "Node.js", "Firebase", "MySQL", "Webpack"],
    },
  ],
  skills: [
    { title: "Frontend", items: ["React", "Next.js", "TypeScript", "JavaScript", "Vite", "Redux", "React Query", "Angular", "Vue"] },
    { title: "Interface e UX", items: ["Tailwind CSS", "Shadcn/UI", "Styled Components", "Material UI", "Acessibilidade", "Figma", "Three.js"] },
    { title: "IA aplicada", items: ["Claude Code", "Google Gemini", "GitHub Copilot", "Prompt Engineering", "LLMs", "RAG"] },
    { title: "DevOps e cloud", items: ["Docker", "Azure DevOps", "Azure Container Apps", "Nginx", "GitHub Actions", "CI/CD"] },
  ],
  education: [
    {
      kind: "degree",
      title: "Pós-graduação em Inteligência Artificial e Ciência de Dados",
      institution: "Universidade São Judas Tadeu",
      period: "2026 · em andamento",
    },
    { kind: "degree", title: "Pós-graduação em Administração Empresarial", period: "Especialização" },
    { kind: "degree", title: "Tecnólogo em Logística", period: "Concluída" },
    {
      kind: "degree",
      title: "Análise e Desenvolvimento de Sistemas",
      institution: "Universidade São Judas Tadeu",
      period: "1 ano cursado · não concluído",
    },
    { kind: "course", title: "ONE (Oracle Next Education): Frontend e Backend", institution: "Oracle + Alura", period: "2022 · 2023" },
    { kind: "course", title: "Interação Humano-Computador e UX", institution: "Universidade São Judas Tadeu", period: "Certificação · 2026" },
    { kind: "course", title: "Acessibilidade com React", institution: "Rocketseat", period: "Certificação · 2025" },
  ],
  workProcess: [
    { title: "Descoberta", description: "Entendo o objetivo, o público e o que define sucesso." },
    { title: "Escopo", description: "Proposta com entregáveis e etapas claras antes de começar." },
    { title: "Desenvolvimento", description: "Entregas frequentes, com código tipado e testado." },
    { title: "Publicação", description: "Deploy, documentação e acompanhamento da evolução." },
  ],
  resumePath: "/documents/curriculo-renan-augusto.pdf",
};
