import type { Profile } from "@/content/types";

export const profile: Profile = {
  headline: "Senior frontend with a product and process mindset.",
  bio: [
    "I'm a senior frontend developer who has worked in web development since October 2018, when I switched careers. I've worked at eight companies on e-commerce, education, health, telecom, industrial and logistics products, building everything from responsive interfaces to corporate dashboards.",
    "I've been the only frontend developer on a product, owning the stack and architecture, and I've worked in larger teams modernizing legacy systems and automating cloud build and deployment.",
    "Before tech, I earned a technologist degree in Logistics and a postgraduate degree in Business Administration. That background helps me understand the operation and the business before designing the screen. I also use AI in my day-to-day engineering work and I'm pursuing a postgraduate degree in Artificial Intelligence and Data Science.",
  ],
  expertise: [
    {
      title: "Interfaces and product",
      description: "Fast, accessible and responsive applications and websites, from component to complete flow.",
      items: ["React and Next.js", "TypeScript", "Tailwind CSS and Shadcn/UI", "Accessibility and UI/UX"],
    },
    {
      title: "Dashboards and integrations",
      description: "Dashboards that organize operational data and connect to APIs and corporate systems.",
      items: ["Data dashboards", "REST APIs", "JWT authentication", "Legacy modernization"],
    },
    {
      title: "Delivery and applied AI",
      description: "Pipelines that ship code to production, and AI used where it brings real gains.",
      items: ["CI/CD and Azure DevOps", "Docker and Azure", "Claude Code, Gemini and Copilot", "Prompt engineering and RAG"],
    },
  ],
  experience: [
    {
      id: "mwm",
      company: "MWM Motores e Geradores",
      role: "Senior Frontend Engineer",
      start: "2025-09",
      end: "2026-09",
      place: "São Paulo · Hybrid",
      summary: "Frontend for corporate and logistics systems, from components to Azure infrastructure.",
      highlights: [
        "Built SPAs and PWAs in React, TypeScript and Vite for MWM Portal and Bio Plantas.",
        "Delivered logistics and quality dashboards that centralized gate management, cooperative members and operational data.",
        "Modernized legacy interfaces to Tailwind CSS and Shadcn/UI, improving responsiveness and accessibility.",
        "Automated build and deployment with Docker, Azure Container Apps, ACR and Azure DevOps pipelines.",
        "Integrated the frontend with Java Spring Boot REST APIs and configured Nginx servers.",
      ],
      stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Shadcn/UI", "Docker", "Azure", "Spring Boot"],
    },
    {
      id: "portal-telemedicina",
      company: "Portal Telemedicina",
      role: "Senior Frontend Engineer",
      start: "2024-10",
      end: "2025-01",
      place: "Barueri, Brazil · Remote",
      summary: "Interfaces for a telemedicine platform built with Angular.",
      highlights: [
        "Built responsive, accessible interfaces with Angular and TypeScript.",
        "Turned layouts into code applying UI/UX principles and tests.",
        "Integrated APIs and services with continuous delivery through GitHub Actions.",
      ],
      stack: ["Angular", "TypeScript", "GitHub Actions"],
    },
    {
      id: "olos",
      company: "Olos Tecnologia",
      role: "Mid-level Frontend Engineer",
      start: "2023-10",
      end: "2024-06",
      place: "São Paulo, Brazil",
      summary: "Web products in React and Next.js focused on UI/UX.",
      highlights: [
        "Built interfaces with React, Next.js, TypeScript, Styled Components and Material UI.",
        "Implemented responsive layouts following UI/UX best practices.",
        "Maintained CI/CD pipelines on GitHub Actions.",
      ],
      stack: ["React", "Next.js", "TypeScript", "Material UI"],
    },
    {
      id: "safira",
      company: "SAFIRA Soluções & Tecnologia",
      role: "Mid-level Frontend Engineer",
      start: "2022-03",
      end: "2023-09",
      place: "São Paulo · Hybrid",
      summary: "Sole frontend developer on the product, owning the stack and architecture.",
      highlights: [
        "Defined the stack and structured the frontend architecture end to end.",
        "Created a reusable React and TypeScript component library, JWT authentication and REST integrations.",
        "Made technical decisions on performance, scalability and security and mentored junior developers.",
        "Worked with AWS and Azure cloud and CI/CD pipelines.",
      ],
      stack: ["React", "TypeScript", "JWT", "AWS", "Azure"],
    },
    {
      id: "clude",
      company: "Clude, Cartão de Saúde 360°",
      role: "Frontend Developer Analyst",
      start: "2020-02",
      end: "2022-03",
      place: "São Paulo, Brazil",
      summary: "Health web applications in React.",
      highlights: [
        "Built responsive web applications with React, JavaScript, Sass and Bootstrap.",
        "Delivered solutions focused on usability and user experience.",
      ],
      stack: ["React", "JavaScript", "Sass", "Bootstrap"],
    },
    {
      id: "saraiva",
      company: "Saraiva",
      role: "Frontend Developer",
      start: "2019-12",
      end: "2020-02",
      place: "São Paulo, Brazil",
      summary: "Large retail e-commerce on the VTEX platform.",
      highlights: [
        "Built online store pages and components with HTML, Sass, JavaScript (jQuery) and Vue.js.",
        "Worked with VTEX Admin (CMS, Checkout, Master Data) and VTEX APIs: catalog, checkout, logistics, marketplace, OMS and gift cards.",
      ],
      stack: ["VTEX", "Vue.js", "JavaScript", "jQuery", "Sass", "Gulp"],
    },
    {
      id: "edulabzz",
      company: "Edulabzz",
      role: "Frontend Developer",
      start: "2019-07",
      end: "2019-10",
      place: "São Paulo, Brazil",
      summary: "Web applications for an education technology company.",
      highlights: [
        "Built web interfaces with HTML5, Sass, JavaScript, jQuery, Bootstrap and Material Design.",
        "Automated build tasks and managed packages with npm and Yarn.",
      ],
      stack: ["JavaScript", "jQuery", "Sass", "Bootstrap", "Material Design"],
    },
    {
      id: "smartest",
      company: "Smartest IT Solutions",
      role: "Frontend Developer (Freelance)",
      start: "2018-10",
      end: "2019-06",
      place: "São Paulo, Brazil",
      summary: "First role after switching careers: on-demand web projects.",
      highlights: [
        "Analyzed and fixed bugs and built new features with JavaScript, React, Vue.js, TypeScript and Node.js.",
        "Consumed REST APIs, used Firebase and MySQL and shipped static builds with Webpack.",
      ],
      stack: ["React", "Vue.js", "TypeScript", "Node.js", "Firebase", "MySQL", "Webpack"],
    },
  ],
  skills: [
    { title: "Frontend", items: ["React", "Next.js", "TypeScript", "JavaScript", "Vite", "Redux", "React Query", "Angular", "Vue"] },
    { title: "Interface and UX", items: ["Tailwind CSS", "Shadcn/UI", "Styled Components", "Material UI", "Accessibility", "Figma", "Three.js"] },
    { title: "Applied AI", items: ["Claude Code", "Google Gemini", "GitHub Copilot", "Prompt engineering", "LLMs", "RAG"] },
    { title: "DevOps and cloud", items: ["Docker", "Azure DevOps", "Azure Container Apps", "Nginx", "GitHub Actions", "CI/CD"] },
  ],
  education: [
    {
      kind: "degree",
      title: "Postgraduate degree in Artificial Intelligence and Data Science",
      institution: "Universidade São Judas Tadeu",
      period: "2026 · in progress",
    },
    { kind: "degree", title: "Postgraduate degree in Business Administration", period: "Specialization" },
    { kind: "degree", title: "Technologist degree in Logistics", period: "Completed" },
    {
      kind: "degree",
      title: "Systems Analysis and Development",
      institution: "Universidade São Judas Tadeu",
      period: "1 year completed · not finished",
    },
    { kind: "course", title: "ONE (Oracle Next Education): Frontend and Backend", institution: "Oracle + Alura", period: "2022 · 2023" },
    { kind: "course", title: "Human-Computer Interaction and UX", institution: "Universidade São Judas Tadeu", period: "Certificate · 2026" },
    { kind: "course", title: "Accessibility with React", institution: "Rocketseat", period: "Certificate · 2025" },
  ],
  workProcess: [
    { title: "Discovery", description: "I learn about the goal, the audience and what success looks like." },
    { title: "Scope", description: "A proposal with clear deliverables and stages before we start." },
    { title: "Development", description: "Frequent deliveries with typed, tested code." },
    { title: "Launch", description: "Deployment, documentation and follow-up as the project evolves." },
  ],
  resumePath: "/documents/resume-renan-augusto.pdf",
};
