import type { Profile } from "@/content/types";

export const profile: Profile = {
  headline: "Senior frontend with a product and process mindset.",
  bio: [
    "I'm a senior frontend developer working with React, Next.js and TypeScript since 2020. I've worked on health, telecom, industrial and logistics products, building everything from responsive interfaces to corporate dashboards.",
    "I've been the only frontend developer on a product, owning the stack and architecture, and I've worked in larger teams modernizing legacy systems and automating cloud build and deployment.",
    "My earlier background in logistics and business processes helps me understand the operation before designing the screen. I also use AI in my day-to-day engineering work and I'm pursuing a postgraduate degree in Artificial Intelligence and Data Science.",
  ],
  expertise: [
    {
      title: "Interfaces and product",
      description: "Fast, accessible and responsive applications and websites, from component to complete flow.",
      items: ["React and Next.js", "TypeScript", "Tailwind CSS and Shadcn/UI", "Accessibility and UI/UX"],
    },
    {
      title: "Dashboards and integrations",
      description: "Dashboards that organize operational data and connect to APIs and corporate systems.",
      items: ["Data dashboards", "REST APIs", "JWT authentication", "Legacy modernization"],
    },
    {
      title: "Delivery and applied AI",
      description: "Pipelines that ship code to production, and AI used where it brings real gains.",
      items: ["CI/CD and Azure DevOps", "Docker and Azure", "Claude Code, Gemini and Copilot", "Prompt engineering and RAG"],
    },
  ],
  experience: [
    {
      id: "mwm",
      company: "MWM Motores e Geradores",
      role: "Senior Frontend Engineer",
      start: "2025-09",
      end: "2026-09",
      place: "São Paulo · Hybrid",
      summary: "Frontend for corporate and logistics systems, from components to Azure infrastructure.",
      highlights: [
        "Built SPAs and PWAs in React, TypeScript and Vite for MWM Portal and Bio Plantas.",
        "Delivered logistics and quality dashboards that centralized gate management, cooperative members and operational data.",
        "Modernized legacy interfaces to Tailwind CSS and Shadcn/UI, improving responsiveness and accessibility.",
        "Automated build and deployment with Docker, Azure Container Apps, ACR and Azure DevOps pipelines.",
        "Integrated the frontend with Java Spring Boot REST APIs and configured Nginx servers.",
      ],
      stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "Shadcn/UI", "Docker", "Azure", "Spring Boot"],
    },
    {
      id: "portal-telemedicina",
      company: "Portal Telemedicina",
      role: "Senior Frontend Engineer",
      start: "2024-10",
      end: "2025-01",
      place: "Barueri, Brazil · Remote",
      summary: "Interfaces for a telemedicine platform built with Angular.",
      highlights: [
        "Built responsive, accessible interfaces with Angular and TypeScript.",
        "Turned layouts into code applying UI/UX principles and tests.",
        "Integrated APIs and services with continuous delivery through GitHub Actions.",
      ],
      stack: ["Angular", "TypeScript", "GitHub Actions"],
    },
    {
      id: "olos",
      company: "Olos Tecnologia",
      role: "Mid-level Frontend Engineer",
      start: "2023-10",
      end: "2024-06",
      place: "São Paulo, Brazil",
      summary: "Web products in React and Next.js focused on UI/UX.",
      highlights: [
        "Built interfaces with React, Next.js, TypeScript, Styled Components and Material UI.",
        "Implemented responsive layouts following UI/UX best practices.",
        "Maintained CI/CD pipelines on GitHub Actions.",
      ],
      stack: ["React", "Next.js", "TypeScript", "Material UI"],
    },
    {
      id: "safira",
      company: "SAFIRA Soluções & Tecnologia",
      role: "Mid-level Frontend Engineer",
      start: "2022-03",
      end: "2023-09",
      place: "São Paulo · Hybrid",
      summary: "Sole frontend developer on the product, owning the stack and architecture.",
      highlights: [
        "Defined the stack and structured the frontend architecture end to end.",
        "Created a reusable React and TypeScript component library, JWT authentication and REST integrations.",
        "Made technical decisions on performance, scalability and security and mentored junior developers.",
        "Worked with AWS and Azure cloud and CI/CD pipelines.",
      ],
      stack: ["React", "TypeScript", "JWT", "AWS", "Azure"],
    },
    {
      id: "clude",
      company: "Clude, Cartão de Saúde 360°",
      role: "Frontend Developer Analyst",
      start: "2020-02",
      end: "2022-03",
      place: "São Paulo, Brazil",
      summary: "Health web applications in React.",
      highlights: [
        "Built responsive web applications with React, JavaScript, Sass and Bootstrap.",
        "Delivered solutions focused on usability and user experience.",
      ],
      stack: ["React", "JavaScript", "Sass", "Bootstrap"],
    },
  ],
  skills: [
    { title: "Frontend", items: ["React", "Next.js", "TypeScript", "JavaScript", "Vite", "Redux", "React Query", "Angular", "Vue"] },
    { title: "Interface and UX", items: ["Tailwind CSS", "Shadcn/UI", "Styled Components", "Material UI", "Accessibility", "Figma", "Three.js"] },
    { title: "Applied AI", items: ["Claude Code", "Google Gemini", "GitHub Copilot", "Prompt engineering", "LLMs", "RAG"] },
    { title: "DevOps and cloud", items: ["Docker", "Azure DevOps", "Azure Container Apps", "Nginx", "GitHub Actions", "CI/CD"] },
  ],
  education: [
    {
      title: "Postgraduate degree in Artificial Intelligence and Data Science",
      institution: "Universidade São Judas Tadeu",
      period: "2026 · in progress",
    },
    { title: "Systems Analysis and Development", institution: "Universidade São Judas Tadeu", period: "Undergraduate degree" },
    { title: "Human-Computer Interaction and UX", institution: "Universidade São Judas Tadeu", period: "Certificate · 2026" },
    { title: "Accessibility with React", institution: "Rocketseat", period: "Certificate · 2025" },
  ],
  workProcess: [
    { title: "Discovery", description: "I learn about the goal, the audience and what success looks like." },
    { title: "Scope", description: "A proposal with clear deliverables and stages before we start." },
    { title: "Development", description: "Frequent deliveries with typed, tested code." },
    { title: "Launch", description: "Deployment, documentation and follow-up as the project evolves." },
  ],
  resumePath: "/documents/resume-renan-augusto.pdf",
};
