import type { ProjectBase } from "@/features/projects/types";

const github = (repo: string) => `https://github.com/renanfrontend/${repo}`;

/**
 * Projetos confirmados a partir dos repositórios públicos de Renan no GitHub.
 * Links verificados em 06/10/2026. A ordem define a exibição.
 */
export const projectsBase: ProjectBase[] = [
  {
    id: "logiflow-3d",
    slug: "logiflow-3d",
    category: "dashboard",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Vite", "Cloudflare Workers"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/logiflow.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("logiflow-3d"),
    liveUrl: "https://renanfrontend.github.io/logiflow-3d/",
  },
  {
    id: "visionstock-ai",
    slug: "visionstock-ai",
    category: "ai",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "React Three Fiber", "Zod", "Vitest", "Gemini API"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/visionstock.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("visionstock-ai"),
    liveUrl: "https://visionstock-ai-nine.vercel.app",
  },
  {
    id: "gemini-beyond-prompts",
    slug: "gemini-beyond-prompts",
    category: "ai",
    technologies: ["Next.js", "React", "TypeScript", "Gemini API", "RAG", "LangGraph", "Tailwind CSS"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/gemini.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("gemini-beyond-prompts"),
    liveUrl: "https://gemini-beyond-prompts.vercel.app",
  },
  {
    id: "fnaf-web",
    slug: "fnaf-web",
    category: "games",
    technologies: ["React", "Vite", "Redux", "JavaScript", "Vitest", "GitHub Actions"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/fnaf.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("fnaf-web"),
    liveUrl: "https://renanfrontend.github.io/fnaf-web/",
  },
  {
    id: "upbeats-karaoke-player",
    slug: "upbeats-karaoke-player",
    category: "web",
    technologies: ["React", "TypeScript", "Web Audio API", "Vite", "Tailwind CSS", "TanStack Query", "i18next", "GitHub Actions"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/karaoke.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("upbeats-karaoke-player"),
    liveUrl: "https://renanfrontend.github.io/upbeats-karaoke-player/",
  },
  {
    id: "mwm-portal",
    slug: "mwm-portal",
    category: "dashboard",
    technologies: ["React", "TypeScript", "Vite", "Tailwind CSS", "Shadcn/UI", "Docker", "Azure DevOps"],
    kind: "professional",
    featured: false,
    gallery: [],
  },
  {
    id: "manor-escape",
    slug: "manor-escape",
    category: "games",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "XState", "Zustand", "Vitest", "Playwright"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/manor.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("manor-escape"),
    liveUrl: "https://renanfrontend.github.io/manor-escape/",
  },
  {
    id: "escudo-cidadao",
    slug: "escudo-cidadao",
    category: "web",
    technologies: ["React", "TypeScript", "Vite", "Material UI", "Node.js", "Express"],
    kind: "personal",
    status: "live",
    featured: true,
    cover: { src: "/images/projects/escudo.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("escudo-cidadao"),
    liveUrl: "https://escudo-cidadao.netlify.app/",
  },
  {
    id: "aster-ct",
    slug: "aster-centro-terapeutico",
    category: "web",
    technologies: ["HTML", "Tailwind CSS", "JavaScript", "SEO"],
    kind: "professional",
    status: "live",
    featured: false,
    cover: { src: "/images/projects/aster.png", width: 1440, height: 900 },
    gallery: [],
    repositoryUrl: github("aster-ct"),
    liveUrl: "https://renanfrontend.github.io/aster-ct/",
  },
  {
    id: "helios-lab",
    slug: "helios-lab",
    category: "games",
    technologies: ["TypeScript", "Vite", "Canvas 2D", "Web Audio API"],
    kind: "personal",
    status: "in-progress",
    featured: false,
    cover: { src: "https://opengraph.githubassets.com/portfolio/renanfrontend/helios-lab", width: 1200, height: 600 },
    gallery: [],
    repositoryUrl: github("helios-lab"),
  },
  {
    id: "gascontrol",
    slug: "gascontrol",
    category: "dashboard",
    technologies: ["React", "TypeScript", "Vite", "Tailwind CSS"],
    kind: "demo",
    status: "in-progress",
    featured: false,
    cover: { src: "/images/projects/gascontrol.png", width: 1325, height: 508 },
    gallery: [],
    repositoryUrl: github("gascontrol-frontend"),
  },
];

/**
 * Ordem dos destaques na home: os melhores projetos com site no ar.
 * Projetos do GitHub com o tópico "portfolio-destaque" entram depois destes.
 */
export const highlightOrder = ["visionstock-ai", "logiflow-3d", "upbeats-karaoke-player", "fnaf-web", "manor-escape", "gemini-beyond-prompts", "escudo-cidadao"];
